# Generated by Django 3.0.2 on 2020-01-28 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cori', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
