# Generated by Django 3.0.2 on 2020-01-28 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cori', '0002_negocio_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
